"""Stub fixtures loaded from ``stub/data.pkl``.

The pickle is generated by :mod:`stub.build` from ``stub/ranobe.json``.
Both files are gitignored — code lives here, data lives on disk only.

If ``data.pkl`` is missing, importing this module raises a clear
``RuntimeError`` with regeneration instructions. There is no synthetic
fallback: the stub data layer is temporary scaffolding for the
design-stub frontend, and a hard failure beats silently rendering a
half-empty home page.
"""

import pickle
from pathlib import Path


_DATA_PATH = Path(__file__).parent / "data.pkl"


if not _DATA_PATH.exists():
    raise RuntimeError(
        f"Stub data not found at {_DATA_PATH}.\n"
        "Run `uv run python -m stub.build` to generate it from "
        "stub/ranobe.json before starting the app."
    )


with open(_DATA_PATH, "rb") as _f:
    _bundle = pickle.load(_f)


NOVELS = _bundle["novels"]
TEAMS = _bundle["teams"]
USERS = _bundle["users"]
TOP_WEEK = _bundle["top_week"]
HOT_NOW = _bundle["hot_now"]
RECENT_COMMENTS = _bundle["recent_comments"]
TAGS = _bundle["tags"]
READER_CHAPTER = _bundle["reader_chapter"]
NOTIFICATIONS = _bundle["notifications"]
COMMENTS = _bundle["comments"]


# ─── Lookups ────────────────────────────────────────────────────────────

def team_by_id(team_id):
    """Return a team dict by its id, or None if not found."""

    if team_id is None:
        return None
    return next((t for t in TEAMS if t["id"] == team_id), None)


def novel_by_id(novel_id):
    """Return a novel dict by its id, or None if not found."""

    if novel_id is None:
        return None
    return next((n for n in NOVELS if n["id"] == novel_id), None)


def user_by_handle(handle):
    """Return a USERS fixture by handle, or None if no fixture exists."""

    if handle is None:
        return None
    return next((u for u in USERS if u["handle"] == handle), None)


def team_member_by_handle(handle):
    """Find a team member by handle across all teams.

    Returns ``(team, member)`` or ``(None, None)``. Useful when a handle
    isn't in USERS but the person is listed as a team member somewhere.
    """

    for team in TEAMS:
        for member in team.get("members", []):
            if member.get("handle") == handle:
                return team, member
    return None, None


def followers_of(handle):
    """Handles that follow ``handle``."""

    return [u["handle"] for u in USERS if handle in u.get("following", [])]


def following_of(handle):
    """Handles that ``handle`` follows."""

    user = user_by_handle(handle)
    return list(user.get("following", [])) if user else []


def user_brief(handle):
    """Lightweight display dict for a handle.

    Resolves through USERS first, then team membership, then None.
    Used for follower / following / mention lists without paying for
    full profile resolution each iteration.
    """

    fixture = user_by_handle(handle)
    if fixture:
        return {
            "handle": fixture["handle"],
            "name": fixture["name"],
            "avatar": fixture.get("avatar"),
            "bio": fixture.get("bio", ""),
            "roles": fixture.get("roles", []),
        }

    team, member = team_member_by_handle(handle)
    if team and member:
        return {
            "handle": member["handle"],
            "name": member["name"],
            "avatar": None,
            "bio": f"{member['role'].capitalize()} у команді {team['name']}.",
            "roles": [member["role"]],
        }

    return None


__all__ = [
    "NOVELS", "TEAMS", "USERS", "TOP_WEEK", "HOT_NOW", "RECENT_COMMENTS",
    "TAGS", "READER_CHAPTER", "NOTIFICATIONS", "COMMENTS",
    "team_by_id", "novel_by_id", "user_by_handle",
    "team_member_by_handle", "followers_of", "following_of", "user_brief",
]
