"""Initial migration

Revision ID: 76863e16e2fd
Revises: 
Create Date: 2025-08-18 20:11:03.208680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76863e16e2fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('login', sa.DateTime(), nullable=False),
    sa.Column('oauth_provider', sa.String(length=64), nullable=True),
    sa.Column('oauth_reference', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lower_username', 'service_users', [sa.literal_column('lower(username)')], unique=True)
    op.create_index(op.f('ix_service_users_oauth_provider'), 'service_users', ['oauth_provider'], unique=False)
    op.create_index(op.f('ix_service_users_oauth_reference'), 'service_users', ['oauth_reference'], unique=False)
    op.create_index(op.f('ix_service_users_username'), 'service_users', ['username'], unique=False)
    op.create_table('service_auth_tokens',
    sa.Column('secret', sa.String(length=64), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_auth_tokens_secret'), 'service_auth_tokens', ['secret'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_auth_tokens_secret'), table_name='service_auth_tokens')
    op.drop_table('service_auth_tokens')
    op.drop_index(op.f('ix_service_users_username'), table_name='service_users')
    op.drop_index(op.f('ix_service_users_oauth_reference'), table_name='service_users')
    op.drop_index(op.f('ix_service_users_oauth_provider'), table_name='service_users')
    op.drop_index('ix_lower_username', table_name='service_users')
    op.drop_table('service_users')
    # ### end Alembic commands ###
