"""Stub fixtures — re-exports from the gitignored ``stub/`` package.

The real data lives in ``stub/data.pkl``, generated by
``uv run python -m stub.build`` from ``stub/ranobe.json``. Both
files are gitignored so we don't ship borrowed translator content
when the project goes open source.

Routers continue importing from ``app.stub_data`` so this shim is
the only seam between application code and the bulk-imported
fixtures. If the data layer ever stops being temporary, this is
where the transition would happen.
"""

from stub.loader import (  # noqa: F401  (re-exports for application code)
    NOVELS,
    TEAMS,
    USERS,
    TOP_WEEK,
    HOT_NOW,
    RECENT_COMMENTS,
    TAGS,
    READER_CHAPTER,
    NOTIFICATIONS,
    COMMENTS,
    team_by_id,
    novel_by_id,
    user_by_handle,
    team_member_by_handle,
    followers_of,
    following_of,
    user_brief,
)
